/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.t45k.gradle.submodule.trial.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
